package com.devmaster.goatfarm.milk.persistence.adapter;

import com.devmaster.goatfarm.milk.application.ports.out.PregnancySnapshotQueryPort;
import com.devmaster.goatfarm.sharedkernel.pregnancy.PregnancySnapshot;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;

import java.time.LocalDate;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

@JdbcTest
@Import(PregnancySnapshotQueryAdapter.class)
class PregnancySnapshotQueryAdapterTest {

    @Autowired
    private NamedParameterJdbcTemplate jdbcTemplate;

    @Autowired
    private PregnancySnapshotQueryPort queryPort;

    @BeforeEach
    void setUp() {
        jdbcTemplate.getJdbcTemplate().execute("DROP TABLE IF EXISTS pregnancy");
        jdbcTemplate.getJdbcTemplate().execute("""
                CREATE TABLE pregnancy (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    farm_id BIGINT NOT NULL,
                    goat_id VARCHAR(50) NOT NULL,
                    status VARCHAR(50) NOT NULL,
                    breeding_date DATE,
                    confirm_date DATE,
                    closed_at DATE
                )
                """);
    }

    @Test
    void shouldKeepPregnancyWhenBreedingDateIsBeforeReferenceEvenIfConfirmDateIsAfter() {
        insertPregnancy(1L, "GOAT-001", "ACTIVE", LocalDate.of(2026, 1, 1), LocalDate.of(2026, 3, 1), null);

        Optional<PregnancySnapshot> result = queryPort.findLatestByFarmIdAndGoatId(
                1L,
                "GOAT-001",
                LocalDate.of(2026, 2, 1)
        );

        assertTrue(result.isPresent());
        assertTrue(result.get().active());
        assertEquals(LocalDate.of(2026, 1, 1), result.get().breedingDate());
    }

    @Test
    void shouldResolveActiveAsOfReferenceDateUsingClosedAt() {
        insertPregnancy(1L, "GOAT-001", "ACTIVE", LocalDate.of(2026, 1, 1), LocalDate.of(2026, 2, 1), LocalDate.of(2026, 2, 15));

        Optional<PregnancySnapshot> beforeClose = queryPort.findLatestByFarmIdAndGoatId(
                1L,
                "GOAT-001",
                LocalDate.of(2026, 2, 10)
        );
        Optional<PregnancySnapshot> afterClose = queryPort.findLatestByFarmIdAndGoatId(
                1L,
                "GOAT-001",
                LocalDate.of(2026, 2, 20)
        );

        assertTrue(beforeClose.isPresent());
        assertTrue(beforeClose.get().active());

        assertTrue(afterClose.isPresent());
        assertFalse(afterClose.get().active());
    }

    @Test
    void shouldPickLatestStartDateOnOrBeforeReferenceDate() {
        insertPregnancy(1L, "GOAT-001", "CLOSED", LocalDate.of(2026, 1, 10), LocalDate.of(2026, 1, 20), LocalDate.of(2026, 2, 1));
        insertPregnancy(1L, "GOAT-001", "ACTIVE", LocalDate.of(2026, 3, 1), LocalDate.of(2026, 3, 10), null);

        Optional<PregnancySnapshot> result = queryPort.findLatestByFarmIdAndGoatId(
                1L,
                "GOAT-001",
                LocalDate.of(2026, 2, 15)
        );

        assertTrue(result.isPresent());
        assertEquals(LocalDate.of(2026, 1, 10), result.get().breedingDate());
        assertFalse(result.get().active());
    }

    private void insertPregnancy(Long farmId,
                                 String goatId,
                                 String status,
                                 LocalDate breedingDate,
                                 LocalDate confirmDate,
                                 LocalDate closedAt) {
        MapSqlParameterSource params = new MapSqlParameterSource()
                .addValue("farmId", farmId)
                .addValue("goatId", goatId)
                .addValue("status", status)
                .addValue("breedingDate", breedingDate)
                .addValue("confirmDate", confirmDate)
                .addValue("closedAt", closedAt);

        jdbcTemplate.update("""
                INSERT INTO pregnancy (farm_id, goat_id, status, breeding_date, confirm_date, closed_at)
                VALUES (:farmId, :goatId, :status, :breedingDate, :confirmDate, :closedAt)
                """, params);
    }
}

