package com.devmaster.goatfarm.authority.business;
import com.devmaster.goatfarm.authority.application.ports.out.*;
import com.devmaster.goatfarm.authority.business.bo.*;
import com.devmaster.goatfarm.authority.business.mapper.AuthorityBusinessMapper;
import com.devmaster.goatfarm.config.exceptions.custom.*;
import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.Mock; import org.mockito.junit.jupiter.MockitoExtension;
import java.time.*; import java.util.*; import static org.assertj.core.api.Assertions.assertThat; import static org.junit.jupiter.api.Assertions.assertThrows; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class AuthBusinessCharacterizationTest {
 static final Instant NOW=Instant.parse("2026-09-12T12:00:00Z"); static final UUID FAMILY=UUID.fromString("22222222-2222-2222-2222-222222222222"), TOKEN=UUID.fromString("33333333-3333-3333-3333-333333333333");
 @Mock CredentialAuthenticationPort credentials; @Mock AuthTokenPort authTokens; @Mock UserPersistencePort users; @Mock AuthorityBusinessMapper mapper; @Mock RefreshSessionPersistencePort sessions; AuthBusiness business; AuthorityAccount user; AuthenticatedPrincipal principal;
 @BeforeEach void setUp(){ business=new AuthBusiness(credentials,authTokens,users,mapper,sessions,Clock.fixed(NOW,ZoneOffset.UTC)); user=new AuthorityAccount(7L,"Operator","operator@example.com","12345678901","encoded",Set.of("ROLE_OPERATOR")); principal=new AuthenticatedPrincipal(7L,user.email(),user.name(),user.roles()); }
 @Test void loginIssuesAndPersistsSession(){ var issued=new IssuedRefreshToken("refresh-token",TOKEN,FAMILY,NOW,NOW.plusSeconds(600)); var response=LoginResponseVO.builder().build(); when(credentials.authenticate(user.email(),"secret")).thenReturn(principal); when(users.findById(7L)).thenReturn(Optional.of(user)); when(authTokens.issueAccessToken(principal)).thenReturn("access-token"); when(authTokens.issueRefreshToken(principal,null)).thenReturn(issued); when(authTokens.accessTokenDurationSeconds()).thenReturn(900L); when(sessions.save(any())).thenAnswer(i->{var s=i.getArgument(0,RefreshSessionRecord.class); s.setId(42L); return s;}); when(mapper.toLoginResponseVO(any(),eq("access-token"),eq("refresh-token"),eq(900L))).thenReturn(response); assertThat(business.authenticateUser(LoginRequestVO.builder().email(user.email()).password("secret").build())).isSameAs(response); verify(sessions).save(any(RefreshSessionRecord.class)); }
 @Test void badCredentialsPropagate(){ when(credentials.authenticate(any(),any())).thenThrow(new InvalidArgumentException("Email ou senha inválidos")); assertThrows(InvalidArgumentException.class,()->business.authenticateUser(LoginRequestVO.builder().email(user.email()).password("wrong").build())); verifyNoInteractions(authTokens); }
 @Test void refreshRotationPreservesFamily(){ var claims=new RefreshTokenClaims(user.email(),TOKEN.toString(),FAMILY.toString(),"7","refresh","REFRESH"); var current=session(42L,TOKEN,FAMILY); var replacementToken=new IssuedRefreshToken("new-refresh",UUID.randomUUID(),FAMILY,NOW,NOW.plusSeconds(600)); when(authTokens.decodeRefreshToken("old-refresh")).thenReturn(claims); when(sessions.findByTokenHashForUpdate(any())).thenReturn(Optional.of(current)); when(sessions.consumeIfActive(42L,NOW)).thenReturn(true); when(authTokens.issueAccessToken(principal)).thenReturn("new-access"); when(authTokens.issueRefreshToken(principal,FAMILY)).thenReturn(replacementToken); when(sessions.save(any())).thenAnswer(i->{var s=i.getArgument(0,RefreshSessionRecord.class); s.setId(43L); return s;}); when(authTokens.accessTokenDurationSeconds()).thenReturn(900L); when(mapper.toLoginResponseVO(any(),any(),any(),anyLong())).thenReturn(LoginResponseVO.builder().build()); business.refreshToken(RefreshTokenRequestVO.builder().refreshToken("old-refresh").build()); verify(sessions).setReplacement(42L,43L); }
 @Test void replayRevokesFamily(){ when(authTokens.decodeRefreshToken("replayed")).thenReturn(new RefreshTokenClaims(user.email(),TOKEN.toString(),FAMILY.toString(),"7","refresh","REFRESH")); when(sessions.findByTokenHashForUpdate(any())).thenReturn(Optional.of(session(42L,TOKEN,FAMILY))); when(sessions.consumeIfActive(42L,NOW)).thenReturn(false); assertThrows(UnauthorizedException.class,()->business.refreshToken(RefreshTokenRequestVO.builder().refreshToken("replayed").build())); verify(sessions).revokeFamily(FAMILY,NOW,"refresh_replay_or_inactive"); }
 @Test void invalidRefreshTypeRejected(){ when(authTokens.decodeRefreshToken("access-token")).thenReturn(new RefreshTokenClaims(user.email(),TOKEN.toString(),FAMILY.toString(),"7","access","ROLE_OPERATOR")); assertThrows(UnauthorizedException.class,()->business.refreshToken(RefreshTokenRequestVO.builder().refreshToken("access-token").build())); verify(sessions,never()).findByTokenHashForUpdate(any()); }
 @Test void claimMismatchRejected(){ when(authTokens.decodeRefreshToken("mismatch")).thenReturn(new RefreshTokenClaims(user.email(),UUID.randomUUID().toString(),FAMILY.toString(),"7","refresh","REFRESH")); when(sessions.findByTokenHashForUpdate(any())).thenReturn(Optional.of(session(42L,TOKEN,FAMILY))); assertThrows(UnauthorizedException.class,()->business.refreshToken(RefreshTokenRequestVO.builder().refreshToken("mismatch").build())); verify(sessions,never()).consumeIfActive(any(),any()); }
 @Test void logoutRevokesFamily(){ when(authTokens.decodeRefreshToken("logout-token")).thenReturn(new RefreshTokenClaims(user.email(),TOKEN.toString(),FAMILY.toString(),"7","refresh","REFRESH")); when(sessions.findByTokenHashForUpdate(any())).thenReturn(Optional.of(session(42L,TOKEN,FAMILY))); business.logout(RefreshTokenRequestVO.builder().refreshToken("logout-token").build()); verify(sessions).revokeFamily(FAMILY,NOW,"logout"); }
 private RefreshSessionRecord session(Long id,UUID token,UUID family){ return new RefreshSessionRecord(id,user,"hash",token,family,NOW.minusSeconds(60),NOW.plusSeconds(600),null,null); }
}
