CREATE TABLE lactation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id BIGINT NOT NULL,
    goat_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    pregnancy_start_date DATE,
    dry_start_date DATE,
    dry_at_pregnancy_days INTEGER DEFAULT 90,
    rest_days INTEGER DEFAULT 60,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE milk_production (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id BIGINT NOT NULL,
    goat_id BIGINT NOT NULL,
    lactation_id BIGINT NOT NULL,
    date DATE NOT NULL,
    shift VARCHAR(20) NOT NULL,
    volume_liters NUMERIC(10, 2) NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_milk_production_lactation FOREIGN KEY (lactation_id) REFERENCES lactation(id),
    CONSTRAINT uk_milk_production_daily_shift UNIQUE (farm_id, goat_id, date, shift)
);

CREATE INDEX idx_lactation_farm_goat ON lactation(farm_id, goat_id);
CREATE INDEX idx_milk_production_farm_goat_date ON milk_production(farm_id, goat_id, date);
