-- Reproduction module tables (Pregnancy + Reproductive Event)

CREATE TABLE pregnancy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id BIGINT NOT NULL,
    goat_id VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    breeding_date DATE,
    confirm_date DATE,
    expected_due_date DATE,
    closed_at DATE,
    close_reason VARCHAR(50),
    notes VARCHAR(1000),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE reproductive_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id BIGINT NOT NULL,
    goat_id VARCHAR(50) NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    event_date DATE NOT NULL,
    breeding_type VARCHAR(50),
    breeder_ref VARCHAR(255),
    notes VARCHAR(1000),
    pregnancy_id BIGINT,
    -- Field reserved for future pregnancy check scheduling feature
    check_scheduled_date DATE,
    check_result VARCHAR(50),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_reproductive_event_pregnancy
        FOREIGN KEY (pregnancy_id) REFERENCES pregnancy(id) ON DELETE SET NULL
);

CREATE INDEX idx_pregnancy_farm_goat ON pregnancy(farm_id, goat_id);
CREATE INDEX idx_pregnancy_farm_goat_status ON pregnancy(farm_id, goat_id, status);

CREATE INDEX idx_reproductive_event_farm_goat_date
    ON reproductive_event(farm_id, goat_id, event_date);

CREATE INDEX idx_reproductive_event_farm_goat_type_date
    ON reproductive_event(farm_id, goat_id, event_type, event_date);
