CREATE TABLE articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    slug VARCHAR(220) NOT NULL,
    excerpt VARCHAR(500) NOT NULL,
    content_markdown TEXT NOT NULL,
    category VARCHAR(40) NOT NULL,
    cover_image_url TEXT,
    published BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMP WITHOUT TIME ZONE,
    highlighted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_articles_slug UNIQUE (slug)
);

CREATE INDEX idx_articles_published_published_at ON articles(published, published_at);
CREATE INDEX idx_articles_highlighted ON articles(highlighted);
CREATE INDEX idx_articles_category ON articles(category);
