CREATE TABLE refresh_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    token_id UUID NOT NULL,
    family_id UUID NOT NULL,
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    replaced_by_id BIGINT,
    revoke_reason VARCHAR(80),
    CONSTRAINT uk_refresh_session_token_hash UNIQUE (token_hash),
    CONSTRAINT uk_refresh_session_token_id UNIQUE (token_id),
    CONSTRAINT fk_refresh_session_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_refresh_session_replaced_by FOREIGN KEY (replaced_by_id) REFERENCES refresh_session(id)
);

CREATE INDEX idx_refresh_session_family_id ON refresh_session (family_id);
CREATE INDEX idx_refresh_session_user_id ON refresh_session (user_id);
CREATE INDEX idx_refresh_session_expires_at ON refresh_session (expires_at);
