-- Criação da tabela Event compatível com H2 e PostgreSQL
CREATE TABLE event (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    goat_registration_number VARCHAR(32),
    event_type VARCHAR(64),
    event_date DATE,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_event_goat FOREIGN KEY (goat_registration_number) REFERENCES goat(registration_number)
);
CREATE INDEX idx_event_goat_registration_number ON event(goat_registration_number);

